myPortfolio/myPortfolio/apps/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:comment_id>/', views.detail_comment, name="detail_comment"),
    path('leave_comment/', views.leave_comment, name="leave_comment"),
]

myPortfolio/myPortfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),
]

myPortfolio/myPortfolio/apps/main/models.py
from django.db import models

from django.utils import timezone
import datetime

#models.ForeignKey(name_class, on_delete = models.CASCADE)
class Comment(models.Model):
    author_name = models.CharField('имя автора', max_length=50)
    comment_text = models.CharField('текст комментария', max_length=200)
    date = models.DateTimeField('дата комментария')

    def __str__(self):
        return self.author_name

    def waz_comment_recently(self):
        return self.date >= (timezone.now() - datetime.timedelta(days=7))

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

myPortfolio/myPortfolio/apps/main/views.py
from django.http import  Http404, HttpResponseRedirect
from django.utils import timezone
from django.shortcuts import render
from django.urls import reverse
from .models import Comment
#from django.http import HttpResponse

def index(request):
    latest_comments_list = Comment.objects.order_by('-date')[:5]
    return render(request, 'main/index.html', {
        'latest_comments_list' : latest_comments_list})

def detail_comment(request, comment_id):
    try:
        comment = Comment.objects.get(id=comment_id)
    except:
        raise Http404("Комментария не существует:(")

    return render(request, 'main/detail_comment.html', {'comment' : comment})

def leave_comment(request):
    new_comment = Comment(
        author_name=request.POST['name'],
        comment_text=request.POST['text'],
        date=timezone.now()
    )
    new_comment.save()
    return HttpResponseRedirect(reverse('main:index'))

myPortfolio/myPortfolio/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Моё портфолио{% endblock %}</title>
    {% load staticfiles %}
    <!--<link rel="stylesheet" href="/static/css/bootstrap.min.css" type="text/css">-->
    <link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}" type="text/css">
</head>
<body>
    <div class="jumbotron">
        <h1 class="text-center text-dark">Моё портфолио</h1>
        <div class="container">
            <img src="{% static 'main/image/avatar.jpg' %}" class="img-thumbnail">
        </div>
        <div class="container">
          {% block content %}{% endblock %}
        </div>
    </div>
    <div class="container">
        &copy; Все права защищены 2019
    </div>
</body>
</html>

myPortfolio/myPortfolio/templates/main/detail_comment.html
{% extends 'base.html' %}

{% block title %}Комментарий от '{{comment.author_name}}'{% endblock %}

{% block content %}

<h2>Комментарий от '{{comment.author_name}}'</h2>

<p><b>Содежимое:</b> {{comment.comment_text}}</p>

<!--{{comment.date|date:"d-m-Y"}}-->
<p><b>Дата:</b> <em>{{comment.date}}</em>
{% if comment.waz_comment_recently %}
СВЕЖИЙ КОММЕНТАРИЙ!
{% endif %}
</p>
{% endblock %}

myPortfolio/myPortfolio/templates/main/includes/latest_comments.html
{% block content %}
<p><b>Последние комментарии от:</b>
    {% if latest_comments_list %}
        {% for comment in latest_comments_list %}
            <span><a href="{% url 'main:detail_comment' comment.id %}">{{comment.author_name}}</a>; </span>
        {% endfor %}
    {% else %}
        Нет комментариев :(
    {% endif %}
</p>
{% endblock %}

myPortfolio/myPortfolio/templates/main/index.html
{% extends 'base.html' %}

{% block content %}

<h3 class="text-info" >Оставить комментарий</h3>
<form action="{% url 'main:leave_comment' %}" method="POST">

    {% csrf_token %}

    <input type="text" required placeholder="Ваше имя" name="name"><br>
    <textarea name="text" required placeholder="Текст комментария" cols="30" rows="10"></textarea><br>

    <button type="submit">Отправить</button>
</form>
<hr>
<p>{% include "main/includes/latest_comments.html" %}</p>

{% endblock %}